/**
 * Grunt task for adding a banner
 *
 * ---------------------------------------------------------------
 *
 * For usage docs see:
 *    https://github.com/mattstyles/grunt-banner
 */
module.exports = function(grunt) {
  var pkg = grunt.file.readJSON('package.json');

  grunt.config.set('usebanner', {
    options: {
      position: 'top',
      banner: '/*!\n<%= asciify_title %> ' + pkg.name + ' ' + pkg.version + ' <' + pkg.homepage + '>\n' +
        ' Contributor(s): ' + pkg.contributors + '\n Last Build: ' + grunt.template.today('yyyy-mm-dd') +
        '\n Do not edit this file. It is created from the src/ folder.\n*/\n',
      linebreak: true
    },
    dev: {
      files: {
        src: ['sine-waves.js']
      }
    }
  });

};
